# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Node.js express app to Azure Web App - compact-donuts

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - 'Sprint-[0-9]*'
      - 'patch-[0-9]*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies with yarn
        run: |
          echo 'Get latest yarn'
          yarn set version stable
          echo 'Install dependencies'
          yarn install --immutable

      - name: Remove docs folder from repo
        run: |
          git rm -rf docs 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'unboundmnl-area-2-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .